name: CI Master

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: '8'

    - name: Create tmp dirs
      run: mkdir -p /tmp/tomee-trunk-ubuntu-jvm8

    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: maven-settings-xml-action
      uses: whelk-io/maven-settings-xml-action@v4
      with:
        repositories: '[{ "id": "central-repo", "url": "https://repo.maven.apache.org/maven2" }]'
        plugin_repositories: '[{ "id": "central-plugin-repository", "url": "https://repo.maven.apache.org/maven2" }]'

    - name: Compile with Sanity checks
      run: mvn help:system -U --show-version --fail-at-end -Djava.io.tmpdir=/tmp/tomee-trunk-ubuntu-jvm8 clean install -DfailIfNoTests=false -DskipTests -Pstyle,rat
      env:
        MAVEN_OPTS: -Xmx2048m


